# Runtime fixtures take private banks generated by the user's ROM importer.
# No donor image, geometry, sequence or sample data is embedded in these tests.
add_executable(RR64Mk64ItemRenderSmoke EXCLUDE_FROM_ALL
    tests/rr64_mk64_item_render_smoke.cpp src/rr64_mk64_item_render.cpp
    src/rr64_mk64_item_assets.cpp src/rr64_actor_pose.cpp)
target_include_directories(RR64Mk64ItemRenderSmoke PRIVATE src
    "${N64MODERN_RUNTIME_ROOT}/N64Recomp/include"
    "${N64MODERN_RUNTIME_ROOT}/librecomp/include"
    "${N64MODERN_RUNTIME_ROOT}/ultramodern/include")
target_compile_features(RR64Mk64ItemRenderSmoke PRIVATE cxx_std_20)
add_executable(RR64Mk64ItemAudioSmoke EXCLUDE_FROM_ALL
    tests/rr64_mk64_item_audio_smoke.cpp src/rr64_mk64_item_audio.cpp
    src/rr64_mk64_item_audio_runtime.cpp)
target_include_directories(RR64Mk64ItemAudioSmoke PRIVATE src
    "${N64MODERN_RUNTIME_ROOT}/N64Recomp/include")
target_compile_features(RR64Mk64ItemAudioSmoke PRIVATE cxx_std_20)
add_executable(RR64Mk64ItemImportSmoke EXCLUDE_FROM_ALL
    tests/rr64_mk64_item_import_smoke.cpp src/rr64_import_install.cpp)
target_include_directories(RR64Mk64ItemImportSmoke PRIVATE src
    "${N64MODERN_RUNTIME_ROOT}/thirdparty")
target_compile_features(RR64Mk64ItemImportSmoke PRIVATE cxx_std_20)
