# Build a private copy from this build's generated worker. Never redirect the
# original game's symbols. C++ linkage permits the private OS wrappers to yield
# without /EHsc's extern-C no-throw assumption on Windows.
file(READ "${INPUT}" GENERATED)
file(WRITE "${OUTPUT}" "#include \"rr64_prediction_resource_worker_begin.inc\"\n")
foreach(NAME func_8000C778 func_8000C7D0)
    string(FIND "${GENERATED}" "RECOMP_FUNC void ${NAME}(" START)
    if(START LESS 0)
        message(FATAL_ERROR "Missing replay resource function ${NAME}")
    endif()
    string(SUBSTRING "${GENERATED}" ${START} -1 BODY)
    string(LENGTH "RECOMP_FUNC void ${NAME}(" PREFIX_LENGTH)
    string(SUBSTRING "${BODY}" ${PREFIX_LENGTH} -1 TAIL)
    string(FIND "${TAIL}" "RECOMP_FUNC void " END)
    if(END LESS 0)
        message(FATAL_ERROR "Missing function boundary after ${NAME}")
    endif()
    math(EXPR END "${END}+${PREFIX_LENGTH}")
    string(SUBSTRING "${BODY}" 0 ${END} BODY)
    if(BODY MATCHES "LOOKUP_FUNC|get_function")
        message(FATAL_ERROR "Indirect resource worker dependency")
    endif()
    string(REGEX MATCHALL "[a-zA-Z_][a-zA-Z_0-9]*\\(rdram," CALLS "${BODY}")
    foreach(CALL IN LISTS CALLS)
        if(NOT CALL MATCHES "^(func_8000C778|osSetIntMask_recomp|osInvalDCache_recomp|osSendMesg_recomp|osRecvMesg_recomp|osPiStartDma_recomp)\\(")
            message(FATAL_ERROR "Unregistered resource dependency: ${CALL}")
        endif()
    endforeach()
    string(REPLACE "RECOMP_FUNC void" "void" BODY "${BODY}")
    if(NAME STREQUAL "func_8000C7D0")
        # Native loop boundary follows completion and task release. Never stop
        # between those operations with a worker-owned task in CPU registers.
        if(NOT BODY MATCHES "L_8000C814:")
            message(FATAL_ERROR "Missing resource worker task boundary")
        endif()
        string(REPLACE "L_8000C814:" "L_8000C814:\n    resource_checkpoint();" BODY "${BODY}")
    endif()
    file(APPEND "${OUTPUT}" "${BODY}\n")
endforeach()
file(APPEND "${OUTPUT}" "#include \"rr64_prediction_resource_worker_end.inc\"\n")
