"""Extract the bounded native floor-query closure used by the local importer.

No ROM data or synthetic cells are embedded. Online lookup callbacks are inert
because the helper owns a complete isolated grid. Course hooks remain callable
and the CLI chooses the original or imported-grid policy for each scale stage.
"""
from pathlib import Path
import argparse, hashlib, json, re


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--generated', type=Path, default=root/'build/RecompiledFuncs')
    parser.add_argument('--output', type=Path, default=root/'tools/mk64-importer-contact')
    args = parser.parse_args()
    functions = {}
    for file in args.generated.glob('funcs_*.c'):
        text = file.read_text()
        matches = list(re.finditer(r'RECOMP_FUNC void (\w+)\(', text))
        for i, match in enumerate(matches):
            functions[match[1]] = text[match.start():matches[i+1].start() if i+1 < len(matches) else len(text)]
    selected = set()
    pending = ['func_80014604', 'func_80014DE4']
    while pending:
        name = pending.pop()
        if name in selected:
            continue
        selected.add(name)
        pending.extend(re.findall(r'\b(func_\w+)\(rdram, ctx\)', functions[name]))
    assert len(selected) == 13, 'Audit a changed native-query closure before shipping it'
    source = '\n'.join(functions[name] for name in sorted(selected))
    allowed = {'rr64_online_terrain_query_begin', 'rr64_online_terrain_lookup'}
    assert set(re.findall(r'\brr64_\w+', source)) <= allowed | {
        'rr64_experimental_course_floor_indices', 'rr64_experimental_course_floor_subindices',
        'rr64_experimental_course_floor_cell_allowed'}
    args.output.mkdir(parents=True, exist_ok=True)
    declarations = '\n'.join(f'void {name}(uint8_t*, recomp_context*);' for name in sorted(selected))
    header = '#pragma once\n#include "recomp.h"\n#ifdef __cplusplus\nextern "C" {\n#endif\n'+declarations+'\nvoid _nsqrtf(uint8_t*, recomp_context*);\n#ifdef __cplusplus\n}\n#endif\n'
    (args.output/'native_contact.h').write_text(header)
    stubs = '\n'.join(f'static void {name}(uint8_t* m, recomp_context* c) {{ (void)m; (void)c; }}' for name in sorted(allowed))
    (args.output/'native_contact.c').write_text('// Generated by scripts/generate_mk64_contact_helper.py; native instructions, no ROM assets.\n#include "native_contact.h"\n#include "rr64_experimental_course.hpp"\n'+stubs+'\n'+source)
    proof = dict(functions=sorted(selected), instructions_sha256={name:hashlib.sha256(functions[name].encode()).hexdigest() for name in sorted(selected)}, online_callbacks='isolated complete grid, inert callbacks', embedded_assets=False)
    (args.output/'native_contact_provenance.json').write_text(json.dumps(proof, indent=2)+'\n')


if __name__ == '__main__':
    main()
