from pathlib import Path
import argparse,io,json,zipfile,struct,zlib
parser=argparse.ArgumentParser(description="Generate the ordinary MK64 Race Pack mod descriptor (no ROM assets).")
parser.add_argument('--output',type=Path,default=Path(__file__).resolve().parents[1]/'native/src/rr64_race_pack_mod_manifest.inc')
parser.add_argument('--fixture-output',type=Path)
args=parser.parse_args();out=args.output;H=args.fixture_output
if H:H.mkdir(parents=True,exist_ok=True)
# Original geometric racing flag, no donor-game imagery or texture bytes.
w=h=64;raw=bytearray()
for y in range(h):
 raw.append(0)
 for x in range(w):
  c=(30,34,42,255)
  if 12<=x<=15 and 8<=y<=55:c=(196,202,214,255)
  if 16<=x<54 and 9<=y<41:c=(238,238,232,255) if ((x-16)//8+(y-9)//8)%2==0 else (43,47,55,255)
  raw.extend(c)
def chunk(tag,data):return struct.pack('>I',len(data))+tag+data+struct.pack('>I',zlib.crc32(tag+data)&0xffffffff)
png=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',w,h,8,6,0,0,0))+chunk(b'IDAT',zlib.compress(raw,9))+chunk(b'IEND',b'')
manifest={'game_id':'rr64','id':'rr64_mk64_race_pack','display_name':'MK64 Race Pack','description':'Import all sixteen Mario Kart 64 race courses, scenery, items, sounds and music from your own Mario Kart 64 USA ROM. Select your Road Rash 64 ROM in the launcher first, then choose Import MK64 ROM here. Conversion runs locally and needs no separate tools. Enable or disable this mod before starting the game; restart the application to change it. Online players need matching converted packs.','short_description':'Import optional courses from your own MK64 ROM.','version':'1.1.0','authors':['RoadRash64Recompiled'],'minimum_recomp_version':'0.0.0','enabled_by_default':True}
text='// Generated by scripts/generate_race_pack_mod_descriptor.py.\n// Standard mod descriptor + original geometric thumbnail; no ROM assets.\n'
for default in [False,True]:
 manifest['enabled_by_default']=default
 b=io.BytesIO()
 with zipfile.ZipFile(b,'w',compression=zipfile.ZIP_STORED) as z:
  for name,data in [('mod.json',json.dumps(manifest,separators=(',',':')).encode()),('rr64-course-pack.json',b'{"format":"rr64-installed-course-pack","version":1}'),('thumb.png',png)]:
   info=zipfile.ZipInfo(name,(2026,9,23,0,0,0));info.compress_type=zipfile.ZIP_STORED;z.writestr(info,data)
 payload=b.getvalue()
 if H:(H/('mk64-descriptor-'+str(default).lower()+'.zip')).write_bytes(payload)
 text+='static constexpr unsigned char descriptor_'+('enabled' if default else 'disabled')+'[] = {\n'
 for i in range(0,len(payload),24):text+='    '+','.join(f'0x{x:02x}' for x in payload[i:i+24])+',\n'
 text+='};\n'
out.write_text(text)
if H:(H/'mod-thumbnail.png').write_bytes(png)
print(len(payload),'bytes per ordinary embedded descriptor')

